
###
## 测试模型
POST http://localhost:8080/test/models
Content-Type: application/json

{
  "debug":true,
  "name": "过滤",
  "details": {
    "type": "FILTER",
    "select_fields": [
      "id",
      "name",
      "age"
    ],
    "chain": {
      "conditions": [
        {
          "type": "GT",
          "name": "age",
          "value": 10
        }
      ]
    },
    "source": {
      "type": "TABLE",
      "table_name": "t_person2",
      "schema": "test_srv",
      "fields": [
        "id",
        "name",
        "age"
      ]
    },
    "alias": "f0"
  }
}

### 创建模型
POST http://localhost:8080/models
Content-Type: application/json

{
  "debug": false,
  "name": "并集",
  "details": {
    "type": "UNION",
    "unionFields": {
      "left": [
        {
          "name": "id",
          "alias": "_id0"
        },
        {
          "name": "name",
          "alias": "_name0"
        },
        {
          "name": "age",
          "alias": "_age0"
        }
      ],
      "right": [
        {
          "name": "id",
          "alias": "_id1"
        },
        {
          "name": "name",
          "alias": "_name1"
        },
        {
          "name": "age",
          "alias": "_age1"
        }
      ]
    },
    "left": {
      "type": "TABLE",
      "name": "t_person2",
      "schema": "test_srv",
      "fields": [
        "id",
        "name",
        "age"
      ]
    },
    "right": {
      "type": "TABLE",
      "name": "t_person1",
      "schema": "test_srv",
      "fields": [
        "id",
        "name",
        "age"
      ]
    },
    "alias": "u0"
  }
}


### 设置为模版
GET http://localhost:8080/602500042847412224/templates
Content-Type: application/json

###
GET http://localhost:8080/modelTemplate/602506206024818688
Content-Type: application/json

### 运行模型
GET http://localhost:8080/models/602845307823411200
Content-Type: application/json


### 定义任务
POST http://localhost:8080/602061285677506560/tasks
Content-Type: application/json

{
  "taskType": 0
}

### 运行任务
GET http://localhost:8080/tasks?taskId=602062930276687872
Content-Type: application/json

