### 过滤
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "debug": true,
  "details": {
    "type": "FILTER",
    "select_fields": [
      "id",
      "name",
      "age"
    ],
    "chain": {
      "conditions": [
        {
          "type": "GT",
          "name": "age",
          "value": 10
        }
      ]
    },
    "source": {
      "type": "TABLE",
      "table_name": "t_person2",
      "fields": [
        "id",
        "name",
        "age"
      ]
    },
    "alias": "f0"
  }
}

### 去重
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "debug": false,
  "details": {
    "type":"DISTINCT",
    "distinct_fields": ["age"],
    "source": {
      "type": "TABLE",
      "table_name": "t_person1",
      "fields": ["id","name","age"]
    },
    "alias": "d0"
  }
}

### 关联
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "debug": true,
  "details": {
    "type": "LEFT_JOIN",
    "join_fields": {
      "left": ["id","name"],
      "right": ["age"]
    },
    "on": [
      {
        "left": "name",
        "right": "name"
      }
    ],
    "left": {
      "type": "FILTER",
      "select_fields": ["id","name","age"],
      "source": {
        "type": "TABLE",
        "table_name": "t_person2",
        "fields": ["id","name","age"]
      },
      "chain": {
        "conditions": [
          {
            "type": "GT",
            "name": "age",
            "value": 5
          }
        ]
      },
      "alias": "v2"
    },
    "right": {
      "type": "FILTER",
      "select_fields": ["id","name","age"],
      "source": {
        "type": "TABLE",
        "table_name": "t_person1",
        "fields": ["id","name","age"]
      },
      "chain": {
        "conditions": [
          {
            "type": "GT",
            "name": "age",
            "value": 10
          }
        ]
      },
      "alias": "v1"
    },
    "alias": "v3"
  }
}

### 统计
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "details": {
    "type": "COUNT",
    "group_by_fields": ["age"],
    "alias": "c0",
    "source": {
      "type": "TABLE",
      "table_name": "t_person1",
      "fields": ["id","name","age"]
    }
  }
}

### 合并列值
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "details": {
    "type": "CONCAT",
    "dialect": "MYSQL",
    "group_by_fields": ["age"],
    "concat_fields": ["name"],
    "alias": "g0",
    "source": {
      "type": "TABLE",
      "table_name": "t_person1",
      "fields": ["id","name","age"]
    }
  }
}

### 差集
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "details": {
    "type": "DIFF",
    "union_fields": {
      "left": ["id","name","age"],
      "right": ["id","name","age"]
    },
    "on": [
      {
        "left": "id",
        "right": "id"
      }
    ],
    "left": {
      "type": "TABLE",
      "table_name": "t_person1",
      "fields": ["id","name","age"]
    },
    "right": {
      "type": "TABLE",
      "table_name": "t_person2",
      "fields": ["id","name","age"]
    },
    "alias": "e0"
  }
}

### 分页
POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "details": {
    "type": "PAGE",
    "dialect": "MYSQL",
    "offset": 20,
    "limit": 10,
    "alias": "p0",
    "source": {
      "type": "TABLE",
      "table_name": "t_person1",
      "fields": [
        "id",
        "name",
        "age"
      ]
    },
    "order_fields": [
      {
        "name": "id",
        "type": "ASC"
      }
    ]
  }
}

###
POST http://localhost:8080/preview
Content-Type: application/json

{
  "debug": false,
  "data": {
    "type": "LEFT_JOIN",
    "join_fields": {
      "left": [
        "id",
        "name"
      ],
      "right": [
        "age"
      ]
    },
    "on": [
      {
        "left": "name",
        "right": "name"
      }
    ],
    "left": {
      "type": "FILTER",
      "select_fields": [
        "id",
        "name",
        "age"
      ],
      "source": {
        "type": "TABLE",
        "table_name": "t_person2",
        "fields": [
          "id",
          "name",
          "age"
        ]
      },
      "condition": {
        "conditions": [
          {
            "type": "GT",
            "name": "age",
            "value": 5
          }
        ]
      },
      "alias": "v2"
    },
    "right": {
      "type": "FILTER",
      "select_fields": [
        "id",
        "name",
        "age"
      ],
      "source": {
        "type": "TABLE",
        "table_name": "t_person1",
        "fields": [
          "id",
          "name",
          "age"
        ]
      },
      "condition": {
        "conditions": [
          {
            "type": "GT",
            "name": "age",
            "value": 10
          }
        ]
      },
      "alias": "v1"
    },
    "alias": "v3"
  }
}

###

POST http://localhost:8080/model/preview
Content-Type: application/json

{
  "debug": false,
  "data": {
    "type": "GROUP_CONCAT",
    "dialect": "MYSQL",
    "group_by_fields": [
      "age"
    ],
    "group_concat_fields": [
      "name"
    ],
    "alias": "g0",
    "source": {
      "type": "TABLE",
      "table_name": "t_person1",
      "fields": [
        "id",
        "name",
        "age"
      ]
    }
  }
}

###

POST http://localhost:8080/model/exec
Content-Type: application/json

{
  "isDebug": false,
  "data": {
    "type": "LEFT_JOIN",
    "join_fields": {
      "left": [
        "id",
        "name"
      ],
      "right": [
        "age"
      ]
    },
    "on": [
      {
        "left": "name",
        "right": "name"
      }
    ],
    "left": {
      "type": "FILTER",
      "select_fields": [
        "id",
        "name",
        "age"
      ],
      "source": {
        "type": "TABLE",
        "table_name": "t_person2",
        "fields": [
          "id",
          "name",
          "age"
        ]
      },
      "condition": {
        "conditions": [
          {
            "type": "GT",
            "name": "age",
            "value": 5
          }
        ]
      },
      "alias": "v2"
    },
    "right": {
      "type": "FILTER",
      "select_fields": [
        "id",
        "name",
        "age"
      ],
      "source": {
        "type": "TABLE",
        "table_name": "t_person1",
        "fields": [
          "id",
          "name",
          "age"
        ]
      },
      "condition": {
        "conditions": [
          {
            "type": "GT",
            "name": "age",
            "value": 10
          }
        ]
      },
      "alias": "v1"
    },
    "alias": "v3"
  }
}

###